services:
    nginx:
        depends_on:
            - node
        build: ./nginx/
        image: 873271/configuration2:configuration2_nginx
        restart: always
        ports:
            - "8080:80"
        container_name: nginx
    node:
        build: ./node/
        image: 873271/configuration2:configuration2_node
        restart: always
        ports:
            - "3000:3000"
        container_name: node