services:
    nginx:
        depends_on:
            - node
        image: 873271/configuration2:configuration2_nginx
        restart: always
        ports:
            - "80:80"
        container_name: nginx
    node:
        image: 873271/configuration2:configuration2_node
        restart: always
        ports:
            - "3000:3000"
        container_name: node